apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  labels:
    app: sample-app
  annotations:
    branch: {{CF_BRANCH_TAG_NORMALIZED}}
    source-repository: {{CF_REPO_NAME}}  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-container
        image: johnsonpan333/samplegoapp:{{CF_BRANCH_TAG_NORMALIZED}}
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      restartPolicy: Always
